<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@taglib prefix="c" uri="jakarta.tags.core"%>
<!DOCTYPE html>
<html lang="en">
<html>
<head>
    <jsp:include page="/WEB-INF/view/includes/head.jsp" />
    <title>Reports</title>
</head>
<body>
<jsp:include page="/WEB-INF/view/includes/header.jsp"/>

<div>
    <h1 class="page-heading">Reports</h1>

    <!-- For Generate Reports -->
    <div class="panel">
        <div class="panel-bar">
            <span class="dot dot-pink"></span><span class="dot dot-yellow"></span><span class="dot dot-yellow"></span>
            <span class="panel-bar-name"reports.exe></span>
        </div>

        <div class="panel-body">
            <form action="${pageContext.request.contextPath}/manager/reports" method="post" class="inline-form">
                <div class="field">
                    <label>Report type</label>
                    <select name="type" required>
                        <option value="REVENUE">Revenue Report</option>
                        <option value="APPOINTMENTS">Appointments</option>
                        <option value="PATIENTS">Patient Report</option>
                    </select>
                </div>
                <button type="submit" class="btn-pill">Generate &raquo;</button>
            </form>
        </div>
    </div>

    <!-- Generate report list -->
    <div class="panel">
        <div class="panel-bar">
            <thead>
                <tr><th>Type</th><th>Generated Date</th><th>Generated By</th></tr>
            </thead>
            <tbody>
                <c:forEach var="r" items="${reports}">
                    <tr>
                        <td>${r.type}</td>
                        <td>${r.generatedDate}</td>
                        <td>${r.generatedByName}</td>
                    </tr>
                </c:forEach>
            </tbody>
        </div>
    </div>
</div>
</body>
</html>
