<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <jsp:include page="/WEB-INF/view/includes/head.jsp" />
    <title>Book Appointment</title>
</head>
<body>
<jsp:include page="/WEB-INF/view/includes/header.jsp"/>

<div class="page-wrap">
    <h1 class="page-heading">Book an Appointment</h1>

    <div class="panel">
        <div class="panel-bar">
            <span class="dot dot-pink"></span><span class="dot dot-yellow"></span><span class="dot dot-green"></span>
            <span class="panel-bar-name">book_appointment.exe</span>
        </div>

        <div class="panel-body">
            <p class="form-sub">Schedule a new patient appointment</p>

            <!-- Search patient by contact number -->
            <div class="form-field">
                <label>Search Patient (by Contact Number)</label>
                <div class="search-row">
                    <input type="text" id="searchContact" placeholder="Type contact number...">
                    <button type="button" class="btn-pill" onclick="searchPatient()">Search</button>
                </div>
            </div>

            <form action="${pageContext.request.contextPath}/receptionist/appointments" method="post">

                <!-- Appointment number (shown, generated by system) -->
                <div class="form-field">
                    <label>Appointment Number</label>
                    <input type="text" value="Auto-generated on booking" disabled>
                </div>

                <!-- Two-column grid for the rest -->
                <div class="form-grid">
                    <div class="form-field">
                        <label>Patient ID</label>
                        <input type="number" name="patientId" id="patientId" required>
                    </div>
                    <div class="form-field">
                        <label>Dentist ID</label>
                        <input type="number" name="dentistId" required>
                    </div>

                    <div class="form-field">
                        <label>Treatment Type</label>
                        <input type="text" name="treatmentType" placeholder="e.g. Cleaning, Filling">
                    </div>
                    <div class="form-field">
                        <label>Appointment Date &amp; Time</label>
                        <input type="datetime-local" name="appointmentDateTime" required>
                    </div>
                </div>

                <button type="submit" class="btn-pill btn-wide">Book Appointment &raquo;</button>
            </form>
        </div>
    </div>
</div>

<script>
    // Simple helper: look the patient up by contact number (optional convenience).
    function searchPatient() {
        var contact = document.getElementById('searchContact').value;
        if (contact) {
            alert('Search patients on the Patients page to find the Patient ID for: ' + contact);
        }
    }
</script>
</body>
</html>
